version: 2
jobs:

  build:
    docker:
      - image: circleci/node:latest-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: install fonts
          command: |
            sudo apt-get update
            sudo apt-get install -y fonts-ipafont-gothic fonts-ipafont-mincho
      - run:
          name: npm run reference
          command: |
            directory=backstop_data/bitmaps_reference
            bash download.sh $directory
            if [ -z "$(ls $directory)" ]; then
                echo "not before artifacts"
                npm run reference
            fi
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - store_artifacts:
          path: backstop_data/bitmaps_test/
          destination: bitmaps_test
      - store_artifacts:
          path: backstop_data/bitmaps_reference/
          destination: bitmaps_reference
      - store_artifacts:
          path: backstop_data/html_report
          destination: html_report
      - store_test_results:
          path: backstop_data/ci_report
workflows:
  version: 2
  normal_test_workflow:
    jobs:
      - build
  every_workflow:
    triggers:
      - schedule:
          cron: "0 * * * *" # UTC
          filters:
            branches:
              only:
                - master
    jobs:
      - build